services:
  api:
    build: .
    container_name: skin_api
    ports:
      - "8000:8000"
    env_file:
      - .env

  ngrok:
    image: ngrok/ngrok:latest
    container_name: skin_ngrok
    command: http http://api:8000 --config=/etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
    depends_on:
      - api
    restart: on-failure